### ISSUE TITLE
Incompatibility with ColorfulMenus

### ISSUE THREAD

**Issue by Myraaleth** [puppy-girl/FishyTracker#1]
V1.1.0 seems to be incompatible with ColorfulMenus mod.
The entire section that should show stars for the sizes you've caught displays as a white box regardless of any settings in ColorfulMenus.
Disabling ColorfulMenus resolves the issue, reverting to FishyTracker V1.0.1 also resolves the issue but fish data seems to get weird (eg, showing all sizes of a fish have been caught as one quality, or no size data is shown at all, loses data between play sessions. V1.0.0 seems ok)

Most recent versions FishyTracker and ColorfulMenus (dark mode)
![image](https://github.com/user-attachments/assets/9a4e2b90-66da-41e8-98c1-138d17071273)

ColorfulMenus disabled
![image](https://github.com/user-attachments/assets/1b4a44ed-b8da-45da-9cb0-e23c287d062d)

FishyTracker V1.0.1, ColorfulMenus enabled
![image](https://github.com/user-attachments/assets/96d1b408-4258-4b29-a589-74292bd9706b)

**Comment by puppy-girl** [comment]
Interesting! I'll see what I can figure out

v1.0.1 fixed some issues but introduced some more: v1.1.0 resolves them so I'd hope for it to work properly with colourful menus

**Comment by kitty-girl** [comment]
this is on my end, ColorfulMenus uses a shader to color text and doesn't take the text's base color into account, SM64Map also has this issue for the coin and star counters
Will be fixed in the next ColorfulMenus update

**Comment by kitty-girl** [comment]
if you do want to fix it on your end instead, separate the table into a new label, and after adding it, do
```gdscript
yield(get_tree(), "idle_frame")
label.material = null
```

**Comment by kitty-girl** [comment]
it's out! you can close this now
