### ISSUE TITLE
Not every catched size/quality is showed

### ISSUE THREAD

**Issue by mastremme** [puppy-girl/FishyTracker#2]
have this kind of issue: it is seen that i did catch at least three different qualities of fish, but it shows me just one on list
![image](https://github.com/user-attachments/assets/3a7f15c4-eb1c-4bd3-8064-48ba50830d15)

Also some fishes don't have the list above their name at all
![image](https://github.com/user-attachments/assets/64e5e86d-eca6-44d2-9767-08c565402d46)

there's always a possibility of me being clueless and not understanding how the mod should work though. I've tried it without any other mods, they are not the case

**Comment by puppy-girl** [comment]
Were the fish caught before or after installing the mod? The game doesn't have this data available so it's only tracking fish in your inventory after the mod was installed ^^~

**Comment by mastremme** [comment]
ooh, right, that's quite logical, thanks
